[package]
# Semantic Versionning is used: https://semver.org/
version = "0.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Tanay Dimri"]

# The title and description fields are primarily for displaying extension info in UI
title = "DEMO UI"
description="A demo UI to understand how an omni extension UI should be structured."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# Location of change log file in target (final) folder of extension, relative to the root. Can also be just a content
# of it instead of file path. More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Demo"

# Keywords for the extension
keywords = ["demo", "ui"]

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/extension_preview_image.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/extension_preview_image.png"

# We only depend on testing framework currently:
[dependencies]
"omni.ui" = {}

[[python.module]]
name = "demo.core"

# Main python module this extension provides, it will be publicly available as "import omni.example.hello".
[[python.module]]
name = "demo.ui"

# Additional python module with tests, to make them discoverable by test system. 
#[[python.module]]
#name = "omni.example.hello.tests"
